2024-06-23 16:00:31,802 - uvicorn.error - INFO - Shutting down
2024-06-23 16:00:31,912 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:00:31,912 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:00:31,912 - uvicorn.error - INFO - Finished server process [29000]
2024-06-23 16:00:32,784 - uvicorn.error - INFO - Started server process [26060]
2024-06-23 16:00:32,784 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:00:32,784 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:01:36,552 - uvicorn.error - INFO - Shutting down
2024-06-23 16:01:36,662 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:01:36,662 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:01:36,662 - uvicorn.error - INFO - Finished server process [26060]
2024-06-23 16:01:46,412 - uvicorn.error - INFO - Started server process [2256]
2024-06-23 16:01:46,412 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:01:46,412 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:02:27,173 - uvicorn.error - INFO - Shutting down
2024-06-23 16:02:27,283 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:02:27,283 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:02:27,283 - uvicorn.error - INFO - Finished server process [2256]
2024-06-23 16:02:28,248 - uvicorn.error - INFO - Started server process [14612]
2024-06-23 16:02:28,248 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:02:28,249 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:04:24,438 - uvicorn.error - INFO - Shutting down
2024-06-23 16:04:24,549 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:04:24,549 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:04:24,549 - uvicorn.error - INFO - Finished server process [14612]
2024-06-23 16:04:25,444 - uvicorn.error - INFO - Started server process [31692]
2024-06-23 16:04:25,444 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:04:25,445 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:09:53,003 - uvicorn.error - INFO - Shutting down
2024-06-23 16:09:53,114 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:09:53,114 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:09:53,114 - uvicorn.error - INFO - Finished server process [31692]
2024-06-23 16:09:54,214 - uvicorn.error - INFO - Started server process [28140]
2024-06-23 16:09:54,214 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:09:54,215 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:11:30,674 - uvicorn.error - INFO - Shutting down
2024-06-23 16:11:30,782 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:11:30,782 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:11:30,782 - uvicorn.error - INFO - Finished server process [28140]
2024-06-23 16:11:31,676 - uvicorn.error - INFO - Started server process [24936]
2024-06-23 16:11:31,676 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:11:31,677 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:11:58,128 - uvicorn.error - INFO - Shutting down
2024-06-23 16:11:58,237 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:11:58,237 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:11:58,237 - uvicorn.error - INFO - Finished server process [24936]
2024-06-23 16:11:59,319 - uvicorn.error - INFO - Started server process [12292]
2024-06-23 16:11:59,319 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:11:59,319 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:12:10,749 - uvicorn.error - INFO - Shutting down
2024-06-23 16:12:10,859 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:12:10,859 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:12:10,860 - uvicorn.error - INFO - Finished server process [12292]
2024-06-23 16:12:11,776 - uvicorn.error - INFO - Started server process [4320]
2024-06-23 16:12:11,777 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:12:11,777 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:12:32,084 - uvicorn.error - INFO - Shutting down
2024-06-23 16:12:32,193 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:12:32,193 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:12:32,193 - uvicorn.error - INFO - Finished server process [4320]
2024-06-23 16:12:33,244 - uvicorn.error - INFO - Started server process [28056]
2024-06-23 16:12:33,245 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:12:33,245 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:12:33,247 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 741, in lifespan
    await receive()
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2024-06-23 16:12:34,186 - uvicorn.error - INFO - Started server process [13132]
2024-06-23 16:12:34,186 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:12:34,187 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:13:16,305 - uvicorn.error - INFO - Shutting down
2024-06-23 16:13:16,412 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:13:16,412 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:13:16,412 - uvicorn.error - INFO - Finished server process [13132]
2024-06-23 16:13:17,284 - uvicorn.error - INFO - Started server process [18196]
2024-06-23 16:13:17,284 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:13:17,284 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:13:40,958 - uvicorn.error - INFO - Shutting down
2024-06-23 16:13:41,067 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:13:41,067 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:13:41,067 - uvicorn.error - INFO - Finished server process [18196]
2024-06-23 16:13:42,036 - uvicorn.error - INFO - Started server process [29128]
2024-06-23 16:13:42,036 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:13:42,037 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:13:42,039 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 741, in lifespan
    await receive()
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2024-06-23 16:13:42,996 - uvicorn.error - INFO - Started server process [15884]
2024-06-23 16:13:42,996 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:13:42,996 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:13:46,284 - uvicorn.error - INFO - Shutting down
2024-06-23 16:13:46,392 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:13:46,392 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:13:46,392 - uvicorn.error - INFO - Finished server process [15884]
2024-06-23 16:13:47,231 - uvicorn.error - INFO - Started server process [12664]
2024-06-23 16:13:47,232 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:13:47,232 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:13:51,925 - uvicorn.error - INFO - Shutting down
2024-06-23 16:13:52,032 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:13:52,032 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:13:52,032 - uvicorn.error - INFO - Finished server process [12664]
2024-06-23 16:13:52,986 - uvicorn.error - INFO - Started server process [21032]
2024-06-23 16:13:52,986 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:13:52,986 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:13:54,071 - uvicorn.error - INFO - Shutting down
2024-06-23 16:13:54,180 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:13:54,180 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:13:54,180 - uvicorn.error - INFO - Finished server process [21032]
2024-06-23 16:13:55,156 - uvicorn.error - INFO - Started server process [33644]
2024-06-23 16:13:55,157 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:13:55,157 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:13,878 - uvicorn.error - INFO - Shutting down
2024-06-23 16:14:13,989 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:14:13,989 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:14:13,989 - uvicorn.error - INFO - Finished server process [33644]
2024-06-23 16:14:14,893 - uvicorn.error - INFO - Started server process [28964]
2024-06-23 16:14:14,893 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:14,893 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:15,001 - uvicorn.error - INFO - Shutting down
2024-06-23 16:14:15,110 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:14:15,110 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:14:15,110 - uvicorn.error - INFO - Finished server process [28964]
2024-06-23 16:14:16,027 - uvicorn.error - INFO - Started server process [20376]
2024-06-23 16:14:16,027 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:16,027 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:16,029 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 741, in lifespan
    await receive()
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2024-06-23 16:14:16,965 - uvicorn.error - INFO - Started server process [24088]
2024-06-23 16:14:16,965 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:16,965 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:16,967 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 741, in lifespan
    await receive()
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2024-06-23 16:14:17,841 - uvicorn.error - INFO - Started server process [16312]
2024-06-23 16:14:17,841 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:17,842 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:18,924 - uvicorn.error - INFO - Shutting down
2024-06-23 16:14:19,032 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:14:19,032 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:14:19,032 - uvicorn.error - INFO - Finished server process [16312]
2024-06-23 16:14:20,001 - uvicorn.error - INFO - Started server process [8772]
2024-06-23 16:14:20,001 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:20,002 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:20,003 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 741, in lifespan
    await receive()
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2024-06-23 16:14:20,819 - uvicorn.error - INFO - Started server process [28960]
2024-06-23 16:14:20,819 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:20,819 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:28,584 - uvicorn.error - INFO - Shutting down
2024-06-23 16:14:28,693 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:14:28,693 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:14:28,693 - uvicorn.error - INFO - Finished server process [28960]
2024-06-23 16:14:29,561 - uvicorn.error - INFO - Started server process [25124]
2024-06-23 16:14:29,562 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:29,562 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:30,544 - uvicorn.error - INFO - Shutting down
2024-06-23 16:14:30,654 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:14:30,654 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:14:30,654 - uvicorn.error - INFO - Finished server process [25124]
2024-06-23 16:14:31,503 - uvicorn.error - INFO - Started server process [21960]
2024-06-23 16:14:31,503 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:31,503 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:35,223 - uvicorn.error - INFO - Shutting down
2024-06-23 16:14:35,332 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:14:35,332 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:14:35,332 - uvicorn.error - INFO - Finished server process [21960]
2024-06-23 16:14:36,162 - uvicorn.error - INFO - Started server process [21412]
2024-06-23 16:14:36,162 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:36,162 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:36,380 - uvicorn.error - INFO - Shutting down
2024-06-23 16:14:36,490 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:14:36,490 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:14:36,490 - uvicorn.error - INFO - Finished server process [21412]
2024-06-23 16:14:37,396 - uvicorn.error - INFO - Started server process [26980]
2024-06-23 16:14:37,397 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:37,397 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:39,268 - uvicorn.error - INFO - Shutting down
2024-06-23 16:14:39,378 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:14:39,378 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:14:39,378 - uvicorn.error - INFO - Finished server process [26980]
2024-06-23 16:14:40,267 - uvicorn.error - INFO - Started server process [31096]
2024-06-23 16:14:40,267 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:40,267 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:14:41,361 - uvicorn.error - INFO - Shutting down
2024-06-23 16:14:41,469 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:14:41,469 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:14:41,470 - uvicorn.error - INFO - Finished server process [31096]
2024-06-23 16:14:42,312 - uvicorn.error - INFO - Started server process [4732]
2024-06-23 16:14:42,312 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:14:42,312 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:15:03,692 - uvicorn.error - INFO - Shutting down
2024-06-23 16:15:03,799 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:15:03,799 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:15:03,799 - uvicorn.error - INFO - Finished server process [4732]
2024-06-23 16:15:04,726 - uvicorn.error - INFO - Started server process [9136]
2024-06-23 16:15:04,726 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:15:04,726 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:15:22,647 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\app\api\routes\auth.py", line 23, in check_uuid
    uuid: UUID = get_uuid(uuid, db)
                 ^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\app\database\crud.py", line 15, in get_uuid
    return db.query(models.UUID).filter(models.UUID.uuid == uuid).first()
                                        ^^^^^^^^^^^^^^^^
AttributeError: type object 'UUID' has no attribute 'uuid'
2024-06-23 16:15:32,144 - uvicorn.error - INFO - Shutting down
2024-06-23 16:15:32,253 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:15:32,253 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:15:32,253 - uvicorn.error - INFO - Finished server process [9136]
2024-06-23 16:15:33,282 - uvicorn.error - INFO - Started server process [25084]
2024-06-23 16:15:33,283 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:15:33,283 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:15:34,873 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\fastapi\routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\app\api\routes\auth.py", line 23, in check_uuid
    uuid: UUID = get_uuid(uuid, db)
                 ^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\AIO-TikTokShop-Backend\app\database\crud.py", line 15, in get_uuid
    return db.query(models.UUID).filter(models.UUID.uuid == uuid).first()
                                        ^^^^^^^^^^^^^^^^
AttributeError: type object 'UUID' has no attribute 'uuid'
2024-06-23 16:15:41,221 - uvicorn.error - INFO - Shutting down
2024-06-23 16:15:41,330 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:15:41,331 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:15:41,331 - uvicorn.error - INFO - Finished server process [25084]
2024-06-23 16:15:42,355 - uvicorn.error - INFO - Started server process [15112]
2024-06-23 16:15:42,355 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:15:42,355 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:20:33,780 - uvicorn.error - INFO - Shutting down
2024-06-23 16:20:33,888 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:20:33,888 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:20:33,888 - uvicorn.error - INFO - Finished server process [15112]
2024-06-23 16:20:34,727 - uvicorn.error - INFO - Started server process [30448]
2024-06-23 16:20:34,728 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:20:34,728 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:21:43,560 - uvicorn.error - INFO - Shutting down
2024-06-23 16:21:43,668 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:21:43,669 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:21:43,669 - uvicorn.error - INFO - Finished server process [30448]
2024-06-23 16:21:44,643 - uvicorn.error - INFO - Started server process [15636]
2024-06-23 16:21:44,644 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:21:44,644 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:27:59,016 - uvicorn.error - INFO - Shutting down
2024-06-23 16:27:59,125 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:27:59,125 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:27:59,125 - uvicorn.error - INFO - Finished server process [15636]
2024-06-23 16:28:00,137 - uvicorn.error - INFO - Started server process [21768]
2024-06-23 16:28:00,137 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:28:00,138 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:32:58,528 - uvicorn.error - INFO - Shutting down
2024-06-23 16:32:58,638 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:32:58,638 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:32:58,638 - uvicorn.error - INFO - Finished server process [21768]
2024-06-23 16:32:59,528 - uvicorn.error - INFO - Started server process [16964]
2024-06-23 16:32:59,529 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:32:59,529 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:33:10,736 - uvicorn.error - INFO - Shutting down
2024-06-23 16:33:10,844 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:33:10,844 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:33:10,844 - uvicorn.error - INFO - Finished server process [16964]
2024-06-23 16:33:11,816 - uvicorn.error - INFO - Started server process [3676]
2024-06-23 16:33:11,817 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:33:11,817 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:35:26,229 - uvicorn.error - INFO - Shutting down
2024-06-23 16:35:26,338 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:35:26,338 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:35:26,338 - uvicorn.error - INFO - Finished server process [3676]
2024-06-23 16:35:27,300 - uvicorn.error - INFO - Started server process [32884]
2024-06-23 16:35:27,301 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:35:27,301 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:35:27,303 - uvicorn.error - ERROR - Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\starlette\routing.py", line 741, in lifespan
    await receive()
  File "D:\GitHub\AIO-TikTokShop-Backend\.venv\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

2024-06-23 16:35:28,268 - uvicorn.error - INFO - Started server process [25868]
2024-06-23 16:35:28,268 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:35:28,268 - uvicorn.error - INFO - Application startup complete.
2024-06-23 16:35:48,086 - uvicorn.error - INFO - Shutting down
2024-06-23 16:35:48,193 - uvicorn.error - INFO - Waiting for application shutdown.
2024-06-23 16:35:48,193 - uvicorn.error - INFO - Application shutdown complete.
2024-06-23 16:35:48,193 - uvicorn.error - INFO - Finished server process [25868]
2024-06-23 16:37:55,606 - uvicorn.error - INFO - Started server process [19344]
2024-06-23 16:37:55,607 - uvicorn.error - INFO - Waiting for application startup.
2024-06-23 16:37:55,607 - uvicorn.error - INFO - Application startup complete.
